AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Hello Lambda Function in TypeScript'

Resources:
  HelloFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: hello-function
      Handler: dist/index.handler
      Runtime: nodejs18.x
      CodeUri: hello-function/
      Description: A simple Lambda function that logs when a new Service is created
      MemorySize: 128
      Timeout: 3
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:GetRecords'
                - 'dynamodb:GetShardIterator'
                - 'dynamodb:DescribeStream'
                - 'dynamodb:ListStreams'
              Resource: '*' 