AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Hello Lambda Function in TypeScript'

Resources:
  HelloFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: hello-function
      Handler: dist/index.handler
      Runtime: nodejs18.x
      CodeUri: hello-function/
      Description: A simple Lambda function that says Hello using TypeScript
      MemorySize: 128
      Timeout: 3 